<?php
$enabled = Mage::getStoreConfig('reviewscouk_reviews_settings/widget/product_widget_enabled',Mage::app()->getStore());
$hide_noreviews = Mage::getStoreConfig('reviewscouk_reviews_settings/widget/product_hide_noreviews',Mage::app()->getStore())? 1 : 0;
$jquery = Mage::getStoreConfig('reviewscouk_reviews_settings/widget/include_jquery',Mage::app()->getStore());
$store_id = Mage::getStoreConfig('reviewscouk_reviews_settings/api/reviews_store_id',Mage::app()->getStore());
$region = Mage::getStoreConfig('reviewscouk_reviews_settings/api/reviews_region',Mage::app()->getStore());
$sku = Mage::registry('current_product')->getSku(); 
$name = Mage::registry('current_product')->getName(); 
if($jquery){
	echo '<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>';
}

$api_url = 'http://dash.reviews.co.uk';
if($region == 'US'){
	$api_url = 'http://dash.review.io';
}

if($store_id && $enabled){
	$url = $api_url."/widgets/productreviewscode?store=".urlencode($store_id)."&sku=".urlencode($sku)."&name=".urlencode($name)."&static=1&hide_noreviews=".$hide_noreviews;
	$ch = curl_init($url);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 2);
	$data = curl_exec($ch);
	curl_close($ch);
	echo $data; 
}
?>
