<h2>Export Product Reviews</h2>

<p>If you already have some product reviews that you would like to import into our system, download the export file here and send it to us at <a href="mailto:support@reviews.co.uk">support@reviews.co.uk</a>.<p>

<p><a style="background:#11507d;color:#fff;padding:8px;border-radius:5px;text-decoration:none;border:1px solid #042f4d;margin:15px 0;display:block;float:left;" href="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/reviews/doexport'); ?>">Download Export File</a></p>
